name: Python Linter and Code Analyser Continuous Integration

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@main

    - name: linting
      uses: programmingwithalex/pylinter@main

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Linting And Code Analyser"
          commit-message: ":art: Analyse and Lint Python code with pylinter"
          body: |
            Linter for React
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/Python_Lint
