name: React Formatter Continuous Integration

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{js,md}

      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v3
        with: 
           token: ${{ secrets.GITHUB_TOKEN }}
           title: "Format React code"
           commit-message: ":art: Format React code with Prettify"
           body: |
             Linter for React
           base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
           branch: actions/React_Prettify
